import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Provider from "@/Provider";
import StoreProvider from "@/redux/StoreProvider";
import AppInit from "@/AppInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Provider>  {/* YE PROVIDER SESSION KA HII */}

          <StoreProvider> {/* YE PROVIDER REDUX KA HII */}


            {/* 💡 YAHA PE IS LIYE CALL KIYE KYUKI KAM PAD SKTA HII KOI BHI PAGE PR IS LIYE  */}
            <AppInit>  {/* HUM DIRECT GETCURRENT USER KO CALL KR SKTE THE BUT LAYOUT KO USE CLIENT NHI BANA THA TO IS LIYE  DUSRI FILE MEA BANA KR WREP KR DIYE */}

              {children}

            </AppInit>

          </StoreProvider>

        </Provider>

        <Toaster />
      </body>
    </html>
  );
}
